# QCTO - Workplace Module

### Project Title: Indian Agriculture Dataset
#### Done By: Khuthadzo Tshikovhele
#### Githublink: https://github.com/katekhuthie/Workplace-individual-project-Khuthadzo
© ExploreAI 2024

---

## Table of Contents

<a href=#BC> Background Context</a>

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Data Collection and Description</a>

<a href=#three>3. Loading Data </a>

<a href=#four>4. Data Cleaning and Filtering</a>

<a href=#five>5. Exploratory Data Analysis (EDA)</a>

<a href=#six>6. Modeling </a>

<a href=#seven>7. Evaluation and Validation</a>

<a href=#eight>8. Final Model</a>

<a href=#nine>9. Conclusion and Future Work</a>

<a href=#ten>10. References</a>

---
 <a id="BC"></a>
## **Background Context**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Introduce the project, outline its goals, and explain its significance.
* **Details:** Include information about the problem domain, the specific questions or challenges the project aims to address, and any relevant background information that sets the stage for the work.

---

District-wise Annual Data on Area, Yield, and Production**

This dataset is organized into two main files:

* **Area, Production, and Yield:**
      Contains annual data for 20 major crops, including cereals, pulses, oilseeds, cotton, sugarcane, and aggregated totals for fruits and vegetables.       Yield figures are derived by dividing total production by the cultivated area.

* **High Yielding Varieties:**
Provides information on the adoption and distribution of high-yielding crop varieties.

The dataset captures the yearly area and production statistics for each crop. The percentage share of each crop’s area is calculated relative to the Gross Cropped Area (GCA), which is computed using a standardized methodology.

---
<a href=#one></a>
## **Importing Packages**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Set up the Python environment with necessary libraries and tools.
* **Details:** List and import all the Python packages that will be used throughout the project such as Pandas for data manipulation, Matplotlib/Seaborn for visualization, scikit-learn for modeling, etc.
---

In [8]:
#Please use code cells to code in and do not forget to comment your code.
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

---
<a href=#two></a>
## **Data Collection and Description**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Describe how the data was collected and provide an overview of its characteristics.
* **Details:** Mention sources of the data, the methods used for collection (e.g., APIs, web scraping, datasets from repositories), and a general description of the dataset including size, scope, and types of data available (e.g., numerical, categorical).
---

In [9]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#three></a>
## **Loading Data**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Load the data into the notebook for manipulation and analysis.
* **Details:** Show the code used to load the data and display the first few rows to give a sense of what the raw data looks like.
---

In [7]:
#Please use code cells to code in and do not forget to comment your code.
#Loading the data
df = pd.read_csv('ICRISAT-District Level Data.csv')
df

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.00,185.00,337.59,44.00,20.00,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.00,409.00,747.71,50.00,26.00,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.30,468.00,841.27,53.70,30.00,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.40,400.80,711.40,49.40,26.50,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.60,473.60,828.55,44.20,29.00,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16141,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,0.0,0.0,0.0,0.00,9.02,9.03,0.48,0.08,0.00
16142,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,0.0,0.0,0.0,0.00,8.63,8.64,0.46,0.04,0.00
16143,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,0.0,0.0,0.0,0.00,6.84,6.85,0.42,0.01,0.00
16144,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.0,0.0,0.0,0.03,6.40,6.43,0.03,0.01,0.00
16145,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00

---
<a href=#four></a>
## **Data Cleaning and Filtering**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Prepare the data for analysis by cleaning and filtering.
* **Details:** Include steps for handling missing values, removing outliers, correcting errors, and possibly reducing the data (filtering based on certain criteria or features).
---

In [5]:
#Please use code cells to code in and do not forget to comment your code.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16146 entries, 0 to 16145
Data columns (total 80 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Dist Code                                    16146 non-null  int64
 1   Year                                         16146 non-null  int64
 2   State Code                                   16146 non-null  int64
 3   State Name                                   16146 non-null  object
 4   Dist Name                                    16146 non-null  object
 5   RICE AREA (1000 ha)                          16146 non-null  float64
 6   RICE PRODUCTION (1000 tons)                  16146 non-null  float64
 7   RICE YIELD (Kg per ha)                       16146 non-null  float64
 8   WHEAT AREA (1000 ha)                         16146 non-null  float64
 9   WHEAT PRODUCTION (1000 tons)                 16146 non-null  float64
 10  WHEAT YIELD (Kg per ha)                      16146 non-null  float64
 11  KHARIF SORGHUM AREA (1000 ha)                16146 non-null  float64
 12  KHARIF SORGHUM PRODUCTION (1000 tons)        16146 non-null  float64
 13  KHARIF SORGHUM YIELD (Kg per ha)             16146 non-null  float64
 14  RABI SORGHUM AREA (1000 ha)                  16146 non-null  float64
 15  RABI SORGHUM PRODUCTION (1000 tons)          16146 non-null  float64
 16  RABI SORGHUM YIELD (Kg per ha)               16146 non-null  float64
 17  SORGHUM AREA (1000 ha)                       16146 non-null  float64
 18  SORGHUM PRODUCTION (1000 tons)               16146 non-null  float64
 19  SORGHUM YIELD (Kg per ha)                    16146 non-null  float64
 20  PEARL MILLET AREA (1000 ha)                  16146 non-null  float64
 21  PEARL MILLET PRODUCTION (1000 tons)          16146 non-null  float64
 22  PEARL MILLET YIELD (Kg per ha)               16146 non-null  float64
 23  MAIZE AREA (1000 ha)                         16146 non-null  float64
 24  MAIZE PRODUCTION (1000 tons)                 16146 non-null  float64
 25  MAIZE YIELD (Kg per ha)                      16146 non-null  float64
 26  FINGER MILLET AREA (1000 ha)                 16146 non-null  float64
 27  FINGER MILLET PRODUCTION (1000 tons)         16146 non-null  float64
 28  FINGER MILLET YIELD (Kg per ha)              16146 non-null  float64
 29  BARLEY AREA (1000 ha)                        16146 non-null  float64
 30  BARLEY PRODUCTION (1000 tons)                16146 non-null  float64
 31  BARLEY YIELD (Kg per ha)                     16146 non-null  float64
 32  CHICKPEA AREA (1000 ha)                      16146 non-null  float64
 33  CHICKPEA PRODUCTION (1000 tons)              16146 non-null  float64
 34  CHICKPEA YIELD (Kg per ha)                   16146 non-null  float64
 35  PIGEONPEA AREA (1000 ha)                     16146 non-null  float64
 36  PIGEONPEA PRODUCTION (1000 tons)             16146 non-null  float64
 37  PIGEONPEA YIELD (Kg per ha)                  16146 non-null  float64
 38  MINOR PULSES AREA (1000 ha)                  16146 non-null  float64
 39  MINOR PULSES PRODUCTION (1000 tons)          16146 non-null  float64
 40  MINOR PULSES YIELD (Kg per ha)               16146 non-null  float64
 41  GROUNDNUT AREA (1000 ha)                     16146 non-null  float64
 42  GROUNDNUT PRODUCTION (1000 tons)             16146 non-null  float64
 43  GROUNDNUT YIELD (Kg per ha)                  16146 non-null  float64
 44  SESAMUM AREA (1000 ha)                       16146 non-null  float64
 45  SESAMUM PRODUCTION (1000 tons)               16146 non-null  float64
 46  SESAMUM YIELD (Kg per ha)                    16146 non-null  float64
 47  RAPESEED AND MUSTARD AREA (1000 ha)          16146 non-null  float64
 48  RAPESEED AND MUSTARD PRODUCTION (1000 tons)  16146 non-null  float64
 49  RAPESEED AND MUSTARD YIELD (Kg per ha)       16146 non-null  float64
 50  SAFFLOWER AREA (1000 ha)                     16146 non-null  float64
 51  SAFFLOWER PRODUCTION (1000 tons)             16146 non-null  float64
 52  SAFFLOWER YIELD (Kg per ha)                  16146 non-null  float64
 53  CASTOR AREA (1000 ha)                        16146 non-null  float64
 54  CASTOR PRODUCTION (1000 tons)                16146 non-null  float64
 55  CASTOR YIELD (Kg per ha)                     16146 non-null  float64
 56  LINSEED AREA (1000 ha)                       16146 non-null  float64
 57  LINSEED PRODUCTION (1000 tons)               16146 non-null  float64
 58  LINSEED YIELD (Kg per ha)                    16146 non-null  float64
 59  SUNFLOWER AREA (1000 ha)                     16146 non-null  float64
 60  SUNFLOWER PRODUCTION (1000 tons)             16146 non-null  float64
 61  SUNFLOWER YIELD (Kg per ha)                  16146 non-null  float64
 62  SOYABEAN AREA (1000 ha)                      16146 non-null  float64
 63  SOYABEAN PRODUCTION (1000 tons)              16146 non-null  float64
 64  SOYABEAN YIELD (Kg per ha)                   16146 non-null  float64
 65  OILSEEDS AREA (1000 ha)                      16146 non-null  float64
 66  OILSEEDS PRODUCTION (1000 tons)              16146 non-null  float64
 67  OILSEEDS YIELD (Kg per ha)                   16146 non-null  float64
 68  SUGARCANE AREA (1000 ha)                     16146 non-null  float64
 69  SUGARCANE PRODUCTION (1000 tons)             16146 non-null  float64
 70  SUGARCANE YIELD (Kg per ha)                  16146 non-null  float64
 71  COTTON AREA (1000 ha)                        16146 non-null  float64
 72  COTTON PRODUCTION (1000 tons)                16146 non-null  float64
 73  COTTON YIELD (Kg per ha)                     16146 non-null  float64
 74  FRUITS AREA (1000 ha)                        16146 non-null  float64
 75  VEGETABLES AREA (1000 ha)                    16146 non-null  float64
 76  FRUITS AND VEGETABLES AREA (1000 ha)         16146 non-null  float64
 77  POTATOES AREA (1000 ha)                      16146 non-null  float64
 78  ONION AREA (1000 ha)                         16146 non-null  float64
 79  FODDER AREA (1000 ha)                        16146 non-null  float64
dtypes: float64(75), int64(3), object(2)
memory usage: 9.9+ MB

In [6]:
df.describe()

,Dist Code,Year,State Code,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),WHEAT YIELD (Kg per ha),KHARIF SORGHUM AREA (1000 ha),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
count,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,...,16146.00000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000
mean,269.769231,1991.496841,9.568562,128.593192,224.889565,1486.924784,77.057946,182.012746,1492.419859,22.632268,...,4500.15306,28.018367,7.229225,124.644823,7.750478,11.086250,18.677877,3.177038,1.194604,21.550328
std,278.309125,15.011185,4.988538,160.078825,326.629828,956.185281,100.394479,348.834254,1081.255367,45.062714,...,3153.97042,74.239648,25.042132,207.681147,13.591135,18.003257,25.881842,8.029509,4.285067,60.062601
min,1.000000,1966.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,78.000000,1978.000000,6.000000,10.400000,9.460000,800.000000,1.770000,2.000000,750.000000,0.000000,...,2000.00000,0.000000,0.000000,0.000000,0.310000,1.600000,2.520000,0.000000,0.060000,0.000000
50%,156.000000,1991.000000,10.000000,66.800000,95.840000,1333.210000,36.800000,42.700000,1347.450000,2.050000,...,4502.21000,0.050000,0.000000,0.000000,2.220000,4.740000,8.945000,0.390000,0.280000,1.200000
75%,241.000000,2005.000000,12.000000,191.390000,315.715000,2113.517500,123.000000,215.192500,2131.580000,20.900000,...,6704.60500,10.097500,2.000000,202.270000,8.790000,12.510000,23.570000,3.150000,0.880000,16.762500
max,917.000000,2017.000000,20.000000,1154.230000,3215.010000,5653.830000,879.490000,4305.500000,5541.520000,334.800000,...,22062.30000,800.890000,376.610000,5000.000000,159.540000,200.060000,240.990000,111.610000,131.350000,1162.660000

In [10]:
# Check for and count duplicated rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicated rows: {duplicate_count}")

Number of duplicated rows: 0

In [11]:
# Summary statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Dist Code,16146.0,269.769231,278.309125,1.0,78.00,156.000,241.0000,917.00
Year,16146.0,1991.496841,15.011185,1966.0,1978.00,1991.000,2005.0000,2017.00
State Code,16146.0,9.568562,4.988538,1.0,6.00,10.000,12.0000,20.00
RICE AREA (1000 ha),16146.0,128.593192,160.078825,-1.0,10.40,66.800,191.3900,1154.23
RICE PRODUCTION (1000 tons),16146.0,224.889565,326.629828,-1.0,9.46,95.840,315.7150,3215.01
...,...,...,...,...,...,...,...,...
VEGETABLES AREA (1000 ha),16146.0,11.086250,18.003257,-1.0,1.60,4.740,12.5100,200.06
FRUITS AND VEGETABLES AREA (1000 ha),16146.0,18.677877,25.881842,-1.0,2.52,8.945,23.5700,240.99
POTATOES AREA (1000 ha),16146.0,3.177038,8.029509,-1.0,0.00,0.390,3.1500,111.61
ONION AREA (1000 ha),16146.0,1.194604,4.285067,-1.0,0.06,0.280,0.8800,131.35
FODDER AREA (1000 ha),16146.0,21.550328,60.062601,-1.0,0.00,1.200,16.7625,1162.66

In [12]:
rice=df.groupby('State Name')['RICE PRODUCTION (1000 tons)'].sum()

top_rice=rice.sort_values(ascending=False).head(7)
top_rice=pd.DataFrame(top_rice)
top_rice=top_rice.reset_index()
top_rice

       State Name  RICE PRODUCTION (1000 tons)
0     West Bengal                    544232.26
1   Uttar Pradesh                    445597.62
2          Punjab                    335040.10
3  Andhra Pradesh                    315185.40
4      Tamil Nadu                    291201.51
5          Orissa                    282532.93
6           Bihar                    231759.00

---
<a href=#five></a>
## **Exploratory Data Analysis (EDA)**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Explore and visualize the data to uncover patterns, trends, and relationships.
* **Details:** Use statistics and visualizations to explore the data. This may include histograms, box plots, scatter plots, and correlation matrices. Discuss any significant findings.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#six></a>
## **Modeling**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Develop and train predictive or statistical models.
* **Details:** Describe the choice of models, feature selection and engineering processes, and show how the models are trained. Include code for setting up the models and explanations of the model parameters.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#seven></a>
## **Evaluation and Validation**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Evaluate and validate the effectiveness and accuracy of the models.
* **Details:** Present metrics used to evaluate the models, such as accuracy, precision, recall, F1-score, etc. Discuss validation techniques employed, such as cross-validation or train/test split.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#eight></a>
## **Final Model**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Present the final model and its performance.
* **Details:** Highlight the best-performing model and discuss its configuration, performance, and why it was chosen over others.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#nine></a>
## **Conclusion and Future Work**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Summarize the findings and discuss future directions.
* **Details:** Conclude with a summary of the results, insights gained, limitations of the study, and suggestions for future projects or improvements in methodology or data collection.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

---
<a href=#ten></a>
## **References**
<a href=#cont>Back to Table of Contents</a>

* **Purpose:** Provide citations and sources of external content.
* **Details:** List all the references and sources consulted during the project, including data sources, research papers, and documentation for tools and libraries used.
---

In [ ]:
#Please use code cells to code in and do not forget to comment your code.

## Additional Sections to Consider

* ### Appendix: 
For any additional code, detailed tables, or extended data visualizations that are supplementary to the main content.

* ### Contributors: 
If this is a group project, list the contributors and their roles or contributions to the project.